version: '3'

services:
  db:
    image: mariadb:latest

    environment:
      MARIADB_ROOT_PASSWORD: password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: ./docker
    volumes:
      - ./src/:/src:rw
