version: '3'

services:
  db:
    image: mariadb:latest
    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: password

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - ./:/app:rw
