version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: budget_flow_api
    ports:
      - "3306:3306"

  cache:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache:/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./src/public:/src/public

  app:
    build:
      context: ./docker
    volumes:
      - ./src/:/src:rw
    depends_on:
      - db
      - cache

volumes:
  db:
    driver: local
  cache:
    driver: local
